FROM ubuntu:18.04

RUN apt-get update -y \
    && apt-get install -y curl build-essential

RUN apt-get install gcc g++ make

RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs

RUN node -v
RUN npm -v

RUN npm install --global yarn

RUN apt-get install -y libsodium-dev

RUN apt-get install -y libzmq3-dev 

RUN apt-get install -y pkg-config

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /root/.cargo/bin/cargo -V

RUN apt-get install -y git

WORKDIR /root/

RUN git clone https://github.com/hyperledger/indy-sdk
WORKDIR /root/indy-sdk/libindy
COPY Cargo.toml .
RUN /root/.cargo/bin/cargo build --release
RUN mv target/release/libindy.so /usr/lib/libindy.so

RUN npm install -g @nestjs/cli

RUN npx -p @aries-framework/node@^0.3 is-indy-installed

RUN mkdir /root/weidy/
WORKDIR /root/weidy/

COPY . .

RUN npm install

CMD [ "npm", "run", "start:dev:issuer" ]
